name: C/C++ Windows

on:
  workflow_dispatch:

jobs:

  build:


    runs-on: windows-latest

    steps:

    - uses: actions/checkout@v4

    - name: install deps
      run:  |
        choco install Make gcc sdl2 sdl2-image -y
    - name: make
      run: make
    - name: make pkg-windows
      run: make pkg-windows

